import { NextRequest, NextResponse } from "next/server";

/**
 * Self-hosted install script endpoint.
 *
 * GET /api/v1/agents/install?key=mdx_xxx         → PowerShell script (Windows)
 * GET /api/v1/agents/install?key=mdx_xxx&os=bash  → Bash script (macOS/Linux)
 *
 * These scripts can be piped directly:
 *   Windows:   powershell -ep bypass -c "irm 'https://server/api/v1/agents/install?key=KEY' | iex"
 *   macOS/Linux: curl -fsSL 'https://server/api/v1/agents/install?key=KEY&os=bash' | sudo bash
 */
export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const apiKey = searchParams.get("key") || "YOUR_API_KEY";
  const os = searchParams.get("os") || "powershell";
  const serverUrl = `${request.nextUrl.protocol}//${request.nextUrl.host}`;

  // Determine script type from path or query
  const isBash = os === "bash" || os === "sh" || request.nextUrl.pathname.endsWith(".sh");

  if (isBash) {
    const script = generateBashScript(apiKey, serverUrl);
    return new NextResponse(script, {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Content-Disposition": "inline; filename=install-mydex.sh",
        "Cache-Control": "no-cache",
      },
    });
  }

  const script = generatePowerShellScript(apiKey, serverUrl);
  return new NextResponse(script, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition": "inline; filename=install-mydex.ps1",
      "Cache-Control": "no-cache",
    },
  });
}

function generatePowerShellScript(apiKey: string, serverUrl: string): string {
  return `# ============================================================
# MyDex Agent - Windows Install Script
# Generated by ${serverUrl}
# ============================================================
# Usage:
#   powershell -ep bypass -c "irm '${serverUrl}/api/v1/agents/install?key=${apiKey}' | iex"
#
# Or save and run:
#   Invoke-WebRequest '${serverUrl}/api/v1/agents/install?key=${apiKey}' -OutFile install.ps1
#   .\\install.ps1
# ============================================================

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

$ApiKey = "${apiKey}"
$ServerUrl = "${serverUrl}"
$InstallDir = "$env:ProgramFiles\\MyDex"
$ConfigDir = "$env:ProgramData\\MyDex"
$ServiceName = "MyDexAgent"
$AgentVersion = "latest"

Write-Host ""
Write-Host "  ===========================================" -ForegroundColor Cyan
Write-Host "     MyDex Agent Installer" -ForegroundColor Cyan
Write-Host "  ===========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Server:  $ServerUrl"
Write-Host "  Target:  $InstallDir"
Write-Host ""

# Check admin privileges
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "[ERROR] This script requires administrator privileges." -ForegroundColor Red
    Write-Host "        Right-click PowerShell and select 'Run as Administrator'." -ForegroundColor Red
    exit 1
}

# Check if already installed
$existingService = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($existingService) {
    Write-Host "[INFO] Existing installation detected. Upgrading..." -ForegroundColor Yellow
    Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2
}

# Step 1: Create directories
Write-Host "[1/5] Creating directories..." -ForegroundColor Yellow
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null

# Step 2: Download agent
Write-Host "[2/5] Downloading MyDex Agent..." -ForegroundColor Yellow
$arch = if ([Environment]::Is64BitOperatingSystem) { "amd64" } else { "386" }
$downloadUrl = "$ServerUrl/downloads/mydex-agent-windows-$arch.exe"

try {
    Invoke-WebRequest -Uri $downloadUrl -OutFile "$InstallDir\\mydex-agent.exe" -UseBasicParsing
    Write-Host "        Downloaded successfully." -ForegroundColor Green
} catch {
    Write-Host "[ERROR] Failed to download agent: $_" -ForegroundColor Red
    Write-Host "        Ensure the server is reachable and binaries are hosted." -ForegroundColor Red
    exit 1
}

# Step 3: Write configuration
Write-Host "[3/5] Writing configuration..." -ForegroundColor Yellow
$config = @{
    api_key = $ApiKey
    server_url = $ServerUrl
    heartbeat_interval = 60
    collection = @{
        processes = @{ enabled = $true; interval = 60 }
        system_state = @{ enabled = $true; interval = 300 }
        software = @{ enabled = $true; interval = 1800 }
        network = @{ enabled = $true; interval = 30 }
        dns = @{ enabled = $true }
        usb = @{ enabled = $true }
    }
    log_level = "info"
}
$config | ConvertTo-Json -Depth 4 | Set-Content "$ConfigDir\\config.json" -Encoding UTF8

# Step 4: Install as Windows Service
Write-Host "[4/5] Installing Windows Service..." -ForegroundColor Yellow
try {
    & "$InstallDir\\mydex-agent.exe" --install --config "$ConfigDir\\config.json"
    Start-Service -Name $ServiceName
    Write-Host "        Service installed and started." -ForegroundColor Green
} catch {
    Write-Host "[WARN] Service installation via agent flag failed. Trying sc.exe..." -ForegroundColor Yellow
    & sc.exe create $ServiceName binPath= """$InstallDir\\mydex-agent.exe"" --config ""$ConfigDir\\config.json""" start= auto
    & sc.exe start $ServiceName
}

# Step 5: Verify
Write-Host "[5/5] Verifying installation..." -ForegroundColor Yellow
Start-Sleep -Seconds 3
$svc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue

Write-Host ""
if ($svc -and $svc.Status -eq "Running") {
    Write-Host "  [OK] MyDex Agent installed and running!" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Service:  $ServiceName (Running)" -ForegroundColor Green
    Write-Host "  Binary:   $InstallDir\\mydex-agent.exe" -ForegroundColor Green
    Write-Host "  Config:   $ConfigDir\\config.json" -ForegroundColor Green
    Write-Host ""
    Write-Host "  The device will appear in your MyDex dashboard shortly." -ForegroundColor Cyan
} else {
    Write-Host "  [WARN] Service may not be running." -ForegroundColor Yellow
    Write-Host "         Check: Get-Service $ServiceName" -ForegroundColor Yellow
    Write-Host "         Logs:  Get-EventLog -LogName Application -Source $ServiceName -Newest 10" -ForegroundColor Yellow
}
Write-Host ""
`;
}

function generateBashScript(apiKey: string, serverUrl: string): string {
  return `#!/usr/bin/env bash
# ============================================================
# MyDex Agent - macOS / Linux Install Script
# Generated by ${serverUrl}
# ============================================================
# Usage:
#   curl -fsSL '${serverUrl}/api/v1/agents/install?key=${apiKey}&os=bash' | sudo bash
#
# Or save and run:
#   curl -fsSL '${serverUrl}/api/v1/agents/install?key=${apiKey}&os=bash' -o install.sh
#   chmod +x install.sh && sudo ./install.sh
# ============================================================

set -euo pipefail

API_KEY="${apiKey}"
SERVER_URL="${serverUrl}"
INSTALL_DIR="/opt/mydex"
CONFIG_DIR="/etc/mydex"
SERVICE_NAME="mydex-agent"

PLATFORM="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"

echo ""
echo "  ==========================================="
echo "     MyDex Agent Installer"
echo "  ==========================================="
echo ""
echo "  Server:   $SERVER_URL"
echo "  Platform: $PLATFORM ($ARCH)"
echo "  Target:   $INSTALL_DIR"
echo ""

# Normalize architecture
case "$ARCH" in
    x86_64|amd64) ARCH="amd64" ;;
    aarch64|arm64) ARCH="arm64" ;;
    armv7l) ARCH="arm" ;;
    *) echo "[ERROR] Unsupported architecture: $ARCH"; exit 1 ;;
esac

# Check root
if [ "$(id -u)" -ne 0 ]; then
    echo "[ERROR] This script must be run as root (use sudo)."
    exit 1
fi

# Check if upgrading
if [ -f "$INSTALL_DIR/mydex-agent" ]; then
    echo "[INFO] Existing installation detected. Upgrading..."
    if [ "$PLATFORM" = "darwin" ]; then
        launchctl unload /Library/LaunchDaemons/work.antifascist.mydex-agent.plist 2>/dev/null || true
    else
        systemctl stop $SERVICE_NAME 2>/dev/null || true
    fi
    sleep 2
fi

# Step 1: Create directories
echo "[1/5] Creating directories..."
mkdir -p "$INSTALL_DIR"
mkdir -p "$CONFIG_DIR"

# Step 2: Download agent
echo "[2/5] Downloading MyDex Agent..."
DOWNLOAD_URL="$SERVER_URL/downloads/mydex-agent-\${PLATFORM}-\${ARCH}"
if command -v curl &>/dev/null; then
    curl -fsSL "$DOWNLOAD_URL" -o "$INSTALL_DIR/mydex-agent"
elif command -v wget &>/dev/null; then
    wget -q "$DOWNLOAD_URL" -O "$INSTALL_DIR/mydex-agent"
else
    echo "[ERROR] Neither curl nor wget found. Install one and retry."
    exit 1
fi
chmod +x "$INSTALL_DIR/mydex-agent"
echo "        Downloaded successfully."

# Step 3: Write configuration
echo "[3/5] Writing configuration..."
cat > "$CONFIG_DIR/config.json" <<ENDCONFIG
{
  "api_key": "$API_KEY",
  "server_url": "$SERVER_URL",
  "heartbeat_interval": 60,
  "collection": {
    "processes": { "enabled": true, "interval": 60 },
    "system_state": { "enabled": true, "interval": 300 },
    "software": { "enabled": true, "interval": 1800 },
    "network": { "enabled": true, "interval": 30 },
    "dns": { "enabled": true },
    "usb": { "enabled": true }
  },
  "log_level": "info"
}
ENDCONFIG

# Step 4: Install as service
echo "[4/5] Installing service..."
if [ "$PLATFORM" = "darwin" ]; then
    # macOS: LaunchDaemon
    cat > /Library/LaunchDaemons/work.antifascist.mydex-agent.plist <<ENDPLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>work.antifascist.mydex-agent</string>
    <key>ProgramArguments</key>
    <array>
        <string>$INSTALL_DIR/mydex-agent</string>
        <string>--config</string>
        <string>$CONFIG_DIR/config.json</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>$INSTALL_DIR</string>
    <key>StandardOutPath</key>
    <string>/var/log/mydex-agent.log</string>
    <key>StandardErrorPath</key>
    <string>/var/log/mydex-agent.err</string>
</dict>
</plist>
ENDPLIST
    launchctl load /Library/LaunchDaemons/work.antifascist.mydex-agent.plist
    echo "        LaunchDaemon installed and loaded."
else
    # Linux: systemd
    cat > /etc/systemd/system/$SERVICE_NAME.service <<ENDSVC
[Unit]
Description=MyDex Monitoring Agent
After=network-online.target
Wants=network-online.target
Documentation=https://antifascist.work/docs

[Service]
Type=simple
ExecStart=$INSTALL_DIR/mydex-agent --config $CONFIG_DIR/config.json
WorkingDirectory=$INSTALL_DIR
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=$SERVICE_NAME

# Security hardening
NoNewPrivileges=false
ProtectSystem=strict
ReadWritePaths=$CONFIG_DIR /var/log

[Install]
WantedBy=multi-user.target
ENDSVC
    systemctl daemon-reload
    systemctl enable $SERVICE_NAME
    systemctl start $SERVICE_NAME
    echo "        systemd service installed and started."
fi

# Step 5: Verify
echo "[5/5] Verifying installation..."
sleep 3

echo ""
if [ "$PLATFORM" = "darwin" ]; then
    if launchctl list | grep -q "work.antifascist.mydex-agent"; then
        echo "  [OK] MyDex Agent installed and running!"
        echo ""
        echo "  Service:  work.antifascist.mydex-agent (LaunchDaemon)"
        echo "  Binary:   $INSTALL_DIR/mydex-agent"
        echo "  Config:   $CONFIG_DIR/config.json"
        echo "  Logs:     /var/log/mydex-agent.log"
    else
        echo "  [WARN] Service may not be running."
        echo "         Check: launchctl list | grep mydex"
    fi
else
    if systemctl is-active --quiet $SERVICE_NAME; then
        echo "  [OK] MyDex Agent installed and running!"
        echo ""
        echo "  Service:  $SERVICE_NAME.service (systemd)"
        echo "  Binary:   $INSTALL_DIR/mydex-agent"
        echo "  Config:   $CONFIG_DIR/config.json"
        echo "  Logs:     journalctl -u $SERVICE_NAME -f"
    else
        echo "  [WARN] Service may not be running."
        echo "         Check: systemctl status $SERVICE_NAME"
        echo "         Logs:  journalctl -u $SERVICE_NAME --no-pager -n 20"
    fi
fi
echo ""
echo "  The device will appear in your MyDex dashboard shortly."
echo ""
`;
}
